/**
 * Helpers PUROS de formato de slug (sin server-only, sin BD) para poder usarse
 * tanto en lib/admin (server) como en los repositories de dominio.
 * La unicidad/reservados se validan en las capas que tienen acceso a BD
 * (generateUniqueSlug / generateUniqueSlugFromBase en '@/lib/admin').
 */

const CATEGORY_SLUG_PREFIX: Record<string, string> = {
  wedding:       'boda',
  baptism:       'bautizo',
  'baby-shower': 'baby-shower',
  birthday:      'cumple',
};

export function categorySlugPrefix(category: string): string {
  return CATEGORY_SLUG_PREFIX[category] ?? category;
}

/** Marcas diacríticas combinantes (acentos tras NFD). Escapes explícitos para
 *  evitar literales unicode frágiles en el código fuente. */
const COMBINING_MARKS = new RegExp('[\\u0300-\\u036f]', 'g');

/** Normaliza texto libre a un fragmento de slug [a-z0-9-] (acentos fuera, ñ→n). */
export function normalizeSlugPart(value: string, maxLength = 30): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(COMBINING_MARKS, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLength)
    .replace(/-+$/g, '');
}

/**
 * Primer nombre de una persona como token de slug ([a-z0-9], máx. 20 chars).
 * null si el nombre está vacío o el token normalizado queda con <2 caracteres.
 */
export function extractFirstNameToken(fullName?: string | null): string | null {
  const first = (fullName ?? '').trim().split(/\s+/)[0] ?? '';
  const token = normalizeSlugPart(first, 20).replace(/-/g, '');
  return token.length >= 2 ? token : null;
}

/**
 * Slug autogenerado `<prefijo-categoría>-<nombre>-<rand5>` — mismo formato que
 * generateBaseSlug de '@/lib/admin' (que delega aquí).
 */
export function buildAutoSlug(category: string, namePart = ''): string {
  const prefix = categorySlugPrefix(category);
  const name = normalizeSlugPart(namePart);
  const random = Math.random().toString(36).slice(2, 7);
  return name ? `${prefix}-${name}-${random}` : `${prefix}-${random}`;
}

/**
 * ¿El slug es autogenerado por el sistema? Cubre el fallback post-pago
 * (`invitacion-…`) y el patrón `boda-<token>-<rand5>` (Parte A / admin auto).
 * Un slug personalizado manualmente nunca matchea estos patrones.
 */
export function isAutoGeneratedSlug(slug: string): boolean {
  return /^invitacion-/.test(slug) || /^boda-[a-z0-9]+-[a-z0-9]{5}$/.test(slug);
}
